"use client";
import { UserProvider } from "./context/user";
import { Inter, Monda, Monofett } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });
const monda = Monda({ subsets: ["latin"], weight: "400" });
const monofett = Monofett({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Game Master's Agenda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId="1060996962870-u0sdh33224nr5hgooleq2danibt5uuai.apps.googleusercontent.com">
          <UserProvider>{children}</UserProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
