# Generated by Django 4.1.7 on 2023-09-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
